blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/enoquesousa/readme-generate/security/advisories/new
    about: Use este canal para reportar vulnerabilidades de seguranÃ§a.
